#!/bin/bash
set -e

repo=sickp/alpine-nginx
latest=1.9.13
version=${1:-$latest}
tags="1.9 mainline latest"

docker build -t ${repo}:${version} --pull versions/${version}
echo "=> Built ${repo}:${version}"
docker build -t ${repo}:${version}-k8s --pull versions/${version}-k8s
echo "=> Built ${repo}:${version}-k8s"

if [[ $latest == $version ]]; then
  for tag in ${tags}; do
    docker tag ${repo}:${version} ${repo}:${tag}
    echo "=> Tagged ${repo}:${tag}"
  done
fi
