#!/bin/bash
set -e

repo=sickp/alpine-nginx
latest=1.9.11
tags="${latest} ${latest}-k8s 1.9 mainline latest"

for tag in ${tags}; do
  docker push ${repo}:${tag}
  echo "=> Pushed ${repo}:${tag}"
done
